### ISSUE TITLE
CCMLogicSolver doesn't accept solver as parameter? 

### ISSUE THREAD

**Issue by danyaljj** [CogComp/Logic2ILP#4]
Why not let the user pass an instance of `ILPSolver` to the constructor of [`CCMLogicSolver`](https://github.com/IllinoisCogComp/Logic2ILP/blob/master/core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/CCMLogicSolver.java) class?

**Comment by haowu40** [comment]
check the  CCMLogicSolver.prepare method, it takes an ILPProblem as input. And in the constructor of ILPProblem, you need to pass an ILPProblem, and write the translated ILP into that object (ILPProblem).

ILPProblem is just a wrapper around the ILPsolver in Illinois-inference, but it keeps the string name mapping, so it is easier introduce more constraints into the ILPProblem.

**Comment by haowu40** [comment]
But I agree, maybe put it into constructor make more sense. We will consider change the constructor.

**Comment by haowu40** [comment]
@danyaljj You can make the PR if you have time, it should be pretty straight forward.

**Comment by haowu40** [comment]
However it should accept our wrapper ILPProblem as a parameter instead of ILPSolver, as we rely on the String name of indicator variable.

**Comment by danyaljj** [comment]
How about this? 
- We pass an instance of `ILPSolver` to the constructor 
- Get rid of `ILPProblem` (and in case any method is missing, move it to `ILPSolver`).

**Comment by danyaljj** [comment]
On a relevant note, it seems unintuitive to me that [`ILPProblem` does bookkeeping of the ILP variable ids.](https://github.com/IllinoisCogComp/Logic2ILP/blob/master/core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/ilp/representation/ILPProblem.java#L17). Shouldn't we get this directly in the constructor of [`CCMLogicSolver`](https://github.com/IllinoisCogComp/Logic2ILP/blob/master/core/src/main/java/edu/illinois/cs/cogcomp/l2ilp/inference/CCMLogicSolver.java#L39)?

**Comment by haowu40** [comment]
Get rid of ILPProblem will require a major change in ILPSolver in illinois-inference. (and probably also require changes in LBJava as the interface change). I'd prefer the current setup, and use anoditional wrapper.

**Comment by haowu40** [comment]
A better name for CCMLogicSolver should be translator. After it translate logic to ILP, I think we should have the ability to add more constraint by hand if we want. As a result , the ILPProblem should be self-contained.

**Comment by danyaljj** [comment]
After thinking a little I think it makes sense to do the bookkeeping the ILP variables inside the ILP solver. Closing ...
